### PR TITLE
Added Sound option to appStopWatch

### PR DESCRIPTION
**Pull request by Fra4prg**
I made some additions to the stop watch and I would appreciate if you could merge this into your project.
All changes are marked with the comment // Fra4prg:

**Description of my changes:**
Added "Smart Sound" option.
"Smart Sound" enables you to hear the number of minutes without having to look on the display.
The idea behind this is that human brain can identify the number of 3 beeps as triple without counting them even if they are very short and fast.
So up to 3 beeps are played slowly and preceeding triples are faster.
For every 10 minutes a sweep sound is preceeding.
A new top left button switches modes between [no sound] - [vibration + sound] - [only sound]

Some examples to show the sequence:
Minute 1: C5
Minute 2: C5-E5
Minute 3: C5-E5-G5
Minute 4: triple - C5
Minute 5: triple - C5-E5
...
Minute 9: triple - triple - C5-E5-G5
Minute 10: sweep
...
Minute 18: sweep - triple - triple - C5-E5
and so on...

As you can see this works well for short times up to 10 minutes then it gets weird...
The idea came up when I was flying model helicopters where I had to control the flight time due to small batteries and must not loose visual contact to my heli model.
So I made a small Arduino based timer called HeliTimer.
But this function fits perfect to the T-watch :-)

Regards
Frank

### CODE REVIEW

**Comment by wfdudley** [comment]
Looks like a well written mod.

**Comment by wfdudley** [comment]
you forgot to upload mp3files.h

I "fixed" it but am not sure if I got the order of the sounds right.

Bill Dudley

This email is free of malware because I run Linux.

**Comment by Fra4prg** [comment]
Oops, sorry. 
Let me check that tomorrow. 

Frank

**Comment by wfdudley** [comment]
You don't need to do a pull request if my version has the sounds in the
same order that yours does.

For that matter, you could just email me the diffs if I do have the sounds
out of order.

Bill Dudley

This email is free of malware because I run Linux.

**Comment by Fra4prg** [comment]
Hi Bill,
you  just need to swap TRIPLE_mp3 and SWEEP_mp3 in the array and sizeofs.
The content of my mp3files.h is:
----------------------------------------------------
// mp3's of beeps of various frequencies
// W.F.Dudley Jr.

#include "sounds/beep__182.h"	// 182 Hz 100 msec
#include "sounds/beep__220.h"	// 220 Hz 100 msec
#include "sounds/beep__279.h"	// etc.
#include "sounds/beep__303.h"
#include "sounds/beep__473.h"
#include "sounds/beep__576.h"
#include "sounds/beep_1050.h"	// 1050 Hz 100 msec
#include "sounds/beep_1050L.h"	// 1050 Hz 200 msec
#include "sounds/beep-chirp1.h"
#include "sounds/C5_L.h"
#include "sounds/E5_L.h"
#include "sounds/G5_L.h"
#include "sounds/TRIPLE.h"
#include "sounds/SWEEP.h"

const unsigned char* const beep_array[] PROGMEM = {
    beep__182_mp3,
    beep__220_mp3,
    beep__279_mp3,
    beep__303_mp3,
    beep__473_mp3,
    beep__576_mp3,
    beep_1050_mp3,
    beep_1050L_mp3,
    beep_chirp1_mp3,
    C5_L_mp3,
    E5_L_mp3,
    G5_L_mp3,
    TRIPLE_mp3,
    SWEEP_mp3
};

const uint16_t beep_sizes[] = {
    sizeof(beep__182_mp3),
    sizeof(beep__220_mp3),
    sizeof(beep__279_mp3),
    sizeof(beep__303_mp3),
    sizeof(beep__473_mp3),
    sizeof(beep__576_mp3),
    sizeof(beep_1050_mp3),
    sizeof(beep_1050L_mp3),
    sizeof(beep_chirp1_mp3),
    sizeof(C5_L_mp3),
    sizeof(E5_L_mp3),
    sizeof(G5_L_mp3),
    sizeof(TRIPLE_mp3),
    sizeof(SWEEP_mp3)
};
----------------------------------------------------

**Comment by Fra4prg** [comment]
again I forgot to sign:

Regards 
Frank

**Comment by wfdudley** [comment]
Frank,

OK, done.  Change is in github.

I also added a new routine for writing arbitrary text in a "button", and
used it for the "silent", "vib+beep", "beep" legends in the "mode" button

Thanks,
Bill Dudley

This email is free of malware because I run Linux.

**Pull request merged**
